### ISSUE TITLE
OcppJsonClients$VersionMismatch

### ISSUE THREAD

**Issue by Vpvladimirov** [NewMotion/ocpp#23]
Hello, I managed to start the server but when I try to start the client and call the server I get this exception:

`log4j:WARN No appenders could be found for logger (com.thenewmotion.ocpp.json.api.client.SimpleClientWebSocketComponent$SimpleClientWebSocketConnection).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" com.thenewmotion.ocpp.json.api.client.OcppJsonClient$VersionMismatch: Could not negotiate a common version for: V16
	at com.thenewmotion.ocpp.json.api.client.OcppJsonClient$$anon$1$$anonfun$1.apply(OcppJsonClient.scala:60)
	at com.thenewmotion.ocpp.json.api.client.OcppJsonClient$$anon$1$$anonfun$1.apply(OcppJsonClient.scala:60)
	at scala.Option.getOrElse(Option.scala:121)
	at com.thenewmotion.ocpp.json.api.client.OcppJsonClient$$anon$1.<init>(OcppJsonClient.scala:59)
	at com.thenewmotion.ocpp.json.api.client.OcppJsonClient.<init>(OcppJsonClient.scala:36)
	at client.Client$$anon$1.<init>(Client.scala:36)
	at client.Client$.delayedEndpoint$client$Client$1(Client.scala:36)
	at client.Client$delayedInit$body.apply(Client.scala:14)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at client.Client$.main(Client.scala:14)
	at client.Client.main(Client.scala)
WebSocket disconnect

Process finished with exit code 1`

Do you know what could be the problem or you need some additional information?

Thank you in advance!

**Comment by reinierl** [comment]
I checked and it works for me! What command did you enter to run the test client? To connect the test client and server together, you have to replace "8017" by "2345" in the example client command from the README.
